file = {"./src/"}
project = "ROBLOX Markup Language"
title = "ROBLOX Markup Language Reference"
package = "net/blacksheepherd/roml"
examples = "examples"
topics = {
	"./topics/01-Introduction.md",
	"./topics/02-BasicRoML.md",
	"./topics/03-LibraryCustomObjects.md",
	"./topics/04-AdvancedRoML.md",
	"./topics/05-RoSS.md",
	"./topics/06-DefiningCustomObjects.md"
}
format = "markdown"
new_type("prop", "Properties")
new_type("event", "Events")
